// YouTube video mappings & helpers for Sujeet Waghela portfolio

export const YOUTUBE_VIDEOS = [
  {
    id: 'jQBoJDCCId4',
    title: 'Space Edit — Sci-Fi Motion Graphics',
    category: 'Motion Graphics',
    type: 'Sci-Fi Visual FX',
    watchUrl: 'https://youtu.be/jQBoJDCCId4',
    embedUrl: 'https://www.youtube.com/embed/jQBoJDCCId4',
    bgEmbedUrl: 'https://www.youtube-nocookie.com/embed/jQBoJDCCId4?autoplay=1&mute=1&loop=1&playlist=jQBoJDCCId4&controls=0&showinfo=0&rel=0&iv_load_policy=3&modestbranding=1&enablejsapi=1&disablekb=1',
    localFallback: '/spaceedit.mp4',
    software: ['Ae', 'Pr'],
    description: 'Cosmic space animation featuring custom galaxy elements, motion tracking, and sci-fi compositing.',
  },
  {
    id: '_NN_eKCju9Q',
    title: 'AVM Edit 2 — Visual FX & Compositing',
    category: 'Anime & Motion Edit',
    type: 'Visual Effects',
    watchUrl: 'https://youtu.be/_NN_eKCju9Q',
    embedUrl: 'https://www.youtube.com/embed/_NN_eKCju9Q',
    bgEmbedUrl: 'https://www.youtube-nocookie.com/embed/_NN_eKCju9Q?autoplay=1&mute=1&loop=1&playlist=_NN_eKCju9Q&controls=0&showinfo=0&rel=0&modestbranding=1&enablejsapi=1&disablekb=1',
    localFallback: '/videos/avm2.mp4',
    software: ['Ae', 'Pr'],
    description: 'Stylized motion graphics edit featuring color isolation, tracking, and custom transition effects.',
  },
  {
    id: 'yUuDwIlAEzQ',
    title: 'AVM Edit 1 — Cinematic Anime Motion Cut',
    category: 'Anime & Motion Edit',
    type: 'Motion FX & Pacing',
    watchUrl: 'https://youtu.be/yUuDwIlAEzQ',
    embedUrl: 'https://www.youtube.com/embed/yUuDwIlAEzQ',
    bgEmbedUrl: 'https://www.youtube-nocookie.com/embed/yUuDwIlAEzQ?autoplay=1&mute=1&loop=1&playlist=yUuDwIlAEzQ&controls=0&showinfo=0&rel=0&modestbranding=1&enablejsapi=1&disablekb=1',
    localFallback: '/videos/avm1.mp4',
    software: ['Ae', 'Pr'],
    description: 'High-octane anime music video edit with dynamic beat synchronization, speed ramping, and optical transitions.',
  },
  {
    id: 'HHrjmFuPkFw',
    title: 'AMV Edit 3 — Dynamic Beat Sync Edit',
    category: 'Anime & Motion Edit',
    type: 'Rhythm & Beat Sync',
    watchUrl: 'https://youtu.be/HHrjmFuPkFw',
    embedUrl: 'https://www.youtube.com/embed/HHrjmFuPkFw',
    bgEmbedUrl: 'https://www.youtube-nocookie.com/embed/HHrjmFuPkFw?autoplay=1&mute=1&loop=1&playlist=HHrjmFuPkFw&controls=0&showinfo=0&rel=0&modestbranding=1&enablejsapi=1&disablekb=1',
    localFallback: '/videos/amv3.mp4',
    software: ['Ae', 'Pr'],
    description: 'Precise rhythm-matched edit with glowing visual overlays, camera shakes, and sound design.',
  },
  {
    id: 'x8WzpprLCAk',
    title: 'Showreel — Motion Graphics & Video Editing Reel',
    category: 'Showreel',
    type: 'Featured Portfolio Showreel',
    watchUrl: 'https://youtu.be/x8WzpprLCAk',
    embedUrl: 'https://www.youtube.com/embed/x8WzpprLCAk',
    bgEmbedUrl: 'https://www.youtube-nocookie.com/embed/x8WzpprLCAk?autoplay=1&mute=1&loop=1&playlist=x8WzpprLCAk&controls=0&showinfo=0&rel=0&modestbranding=1&enablejsapi=1&disablekb=1',
    localFallback: '/videos/showreel.mp4',
    software: ['Ae', 'Pr', 'Ps'],
    description: 'Comprehensive showreel highlighting motion graphics, cinematic pacing, visual effects, and color grading by Sujeet Waghela.',
  },
  {
    id: 'edit4',
    title: 'Edit 4 — Cinematic Creative Cut',
    category: 'Creative Edit',
    type: 'Cinematic Post-Production',
    watchUrl: '',
    embedUrl: '',
    bgEmbedUrl: '',
    localFallback: '/videos/edit4.mp4',
    software: ['Pr', 'Ae'],
    description: 'Atmospheric creative video edit focusing on storytelling pacing, mood grading, and smooth cut transitions.',
  },
];

export const DRIVE_PROFILE_IMAGE = {
  driveShareUrl: 'https://drive.google.com/file/d/1nNtQzvc3Ia3-Km5HfmYBxPRlBdu7AzvN/view?usp=sharing',
  directUrl: 'https://lh3.googleusercontent.com/d/1nNtQzvc3Ia3-Km5HfmYBxPRlBdu7AzvN',
  localFallback: '/sujeet_profile.jpg',
};
